# Generated by Django 6.1 on 2026-08-27 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstanteVirtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estante', models.CharField(max_length=255)),
                ('status_privacidade', models.CharField(default='publico', max_length=50)),
                ('ordem_exibicao', models.IntegerField(default=0)),
                ('tema_visual', models.CharField(default='padrao', max_length=100)),
            ],
            options={
                'verbose_name': 'Estante virtual',
                'verbose_name_plural': 'Estantes virtuais',
                'ordering': ['usuario', 'ordem_exibicao'],
            },
        ),
        migrations.CreateModel(
            name='ItemEstante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao_slot', models.IntegerField(blank=True, null=True)),
                ('data_posicionamento', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Item da estante',
                'verbose_name_plural': 'Itens das estantes',
                'ordering': ['estante', 'posicao_slot'],
            },
        ),
        migrations.CreateModel(
            name='ColecionavelUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicao_caixa', models.CharField(help_text='Ex: MISB lacrado, Aberto p/ exibição, Loose, Caixa avariada', max_length=255)),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('preco_pago', models.DecimalField(decimal_places=2, max_digits=20)),
                ('local_armazenamento', models.CharField(blank=True, max_length=255, null=True)),
                ('status_privacidade', models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado'), ('apenas_link', 'Apenas com link')], default='publico', max_length=20)),
                ('status_negociacao', models.CharField(choices=[('exibicao', 'Só exibição'), ('venda', 'À venda'), ('troca', 'Para troca'), ('venda_ou_troca', 'Venda ou troca')], default='exibicao', max_length=20)),
                ('preco_anunciado', models.DecimalField(blank=True, decimal_places=2, help_text='Preço solicitado (obrigatório se estiver à venda)', max_digits=20, null=True)),
                ('interesses_troca', models.TextField(blank=True, help_text='Descrição opcional dos itens de interesse para troca', null=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='catalogo.modelocolecionavel')),
            ],
            options={
                'verbose_name': 'Colecionável do usuário',
                'verbose_name_plural': 'Colecionáveis dos usuários',
                'ordering': ['-data_inclusao'],
            },
        ),
    ]
