# Generated by Django 6.1 on 2026-08-27 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='colecionavelusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colecionaveis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estantevirtual',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estantes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemestante',
            name='colecionavel_usuario',
            field=models.OneToOneField(help_text='OneToOne: garante que o item fique em apenas 1 slot, como no diagrama original', on_delete=django.db.models.deletion.CASCADE, related_name='posicionamento', to='inventario.colecionavelusuario'),
        ),
        migrations.AddField(
            model_name='itemestante',
            name='estante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='inventario.estantevirtual'),
        ),
    ]
