# Generated by Django 6.1 on 2026-09-11 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_estantevirtual_quantidade_dioramas_diorama'),
    ]

    operations = [
        migrations.AddField(
            model_name='colecionavelusuario',
            name='estado_peca',
            field=models.CharField(default='Não informado', max_length=50),
        ),
        migrations.AddField(
            model_name='colecionavelusuario',
            name='nome_personalizado',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='colecionavelusuario',
            name='nota',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='colecionavelusuario',
            name='personalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ImagemColecionavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagem', models.URLField(max_length=500)),
                ('ordem_exibicao', models.IntegerField(default=0)),
                ('imagem_principal', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('colecionavel_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='inventario.colecionavelusuario')),
            ],
            options={
                'ordering': ['ordem_exibicao', 'pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('imagem_principal', True)), fields=('colecionavel_usuario',), name='unica_principal_inventario')],
            },
        ),
    ]
