# Generated by Django 6.1 on 2026-09-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_colecionavelusuario_estado_peca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemcolecionavel',
            name='arquivo',
            field=models.ImageField(blank=True, upload_to='colecionaveis/%Y/%m/'),
        ),
    ]
