# Generated by Django 6.1 on 2026-09-16 11:46

from django.db import migrations, models


def preservar_dioramas_personalizados(apps, schema_editor):
    Diorama = apps.get_model('inventario', 'Diorama')
    for diorama in Diorama.objects.all():
        titulo_padrao = f"Diorama {diorama.ordem}"
        if diorama.descricao or diorama.titulo != titulo_padrao:
            diorama.configurado = True
            diorama.save(update_fields=['configurado'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_imagemcolecionavel_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='diorama',
            name='configurado',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(preservar_dioramas_personalizados, migrations.RunPython.noop),
    ]
