# Generated by Django 6.1 on 2026-09-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_diorama_por_prateleira'),
    ]

    operations = [
        migrations.AddField(
            model_name='estantevirtual',
            name='diorama_destaque',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
