# Generated by Django 5.2.17 on 2026-09-17 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_selecionar_diorama_destaque'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='colecionavelusuario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='diorama',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='estantevirtual',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='imagemcolecionavel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itemestante',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='colecionavelusuario',
            table='colecionaveis_usuario',
        ),
        migrations.AlterModelTable(
            name='diorama',
            table='dioramas_ia',
        ),
        migrations.AlterModelTable(
            name='estantevirtual',
            table='estantes_virtuais',
        ),
        migrations.AlterModelTable(
            name='imagemcolecionavel',
            table='imagens_colecionaveis',
        ),
        migrations.AlterModelTable(
            name='itemestante',
            table='itens_estante',
        ),
        migrations.CreateModel(
            name='ItemWishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('colecionavel_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salvo_por', to='inventario.colecionavelusuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wishlist_itens',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'colecionavel_usuario'), name='uniq_wishlist_usuario_item')],
            },
        ),
    ]
