# Generated by Django 5.2.17 on 2026-09-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_colecionavelusuario_id_alter_diorama_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estantevirtual',
            name='status_privacidade',
            field=models.CharField(default='privado', max_length=50),
        ),
    ]
