# Generated by Django 5.2.17 on 2026-09-22 11:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_estantevirtual_status_privacidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoEstante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField(help_text='Nota de 1 a 5 estrelas.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, max_length=500)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_estante_feitas', to=settings.AUTH_USER_MODEL)),
                ('estante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='inventario.estantevirtual')),
            ],
            options={
                'verbose_name': 'Avaliação de estante',
                'verbose_name_plural': 'Avaliações de estantes',
                'db_table': 'avaliacoes_estantes',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('estante', 'avaliador'), name='uniq_avaliacao_por_usuario_estante'), models.CheckConstraint(condition=models.Q(('nota__gte', 1), ('nota__lte', 5)), name='avaliacao_estante_nota_entre_1_e_5')],
            },
        ),
    ]
