# Generated by Django 6.1 on 2026-09-22 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioramas_novo', '0003_cenarios_super_herois'),
        ('inventario', '0010_avaliacaoestante'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemestante',
            name='diorama_novo',
            field=models.OneToOneField(blank=True, help_text='Diorama que ocupa uma linha inteira da estante.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posicionamento_prateleira', to='dioramas_novo.dioramageradonovo'),
        ),
        migrations.AlterField(
            model_name='itemestante',
            name='colecionavel_usuario',
            field=models.OneToOneField(blank=True, help_text='OneToOne: garante que o item fique em apenas 1 slot, como no diagrama original', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posicionamento', to='inventario.colecionavelusuario'),
        ),
        migrations.AddConstraint(
            model_name='itemestante',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('colecionavel_usuario__isnull', False), ('diorama_novo__isnull', True)), models.Q(('colecionavel_usuario__isnull', True), ('diorama_novo__isnull', False)), _connector='OR'), name='item_estante_exatamente_um_tipo'),
        ),
        migrations.AddConstraint(
            model_name='itemestante',
            constraint=models.UniqueConstraint(condition=models.Q(('posicao_slot__isnull', False)), fields=('estante', 'posicao_slot'), name='item_estante_slot_unico'),
        ),
        migrations.AddConstraint(
            model_name='itemestante',
            constraint=models.CheckConstraint(condition=models.Q(('diorama_novo__isnull', True), ('posicao_slot__isnull', True), ('posicao_slot__in', [1, 5, 9]), _connector='OR'), name='diorama_apenas_inicio_linha'),
        ),
    ]
