services:
  web:
    build: .
    container_name: forjageek_web
    ports:
      - "8000:8000"
    restart: unless-stopped

    volumes:
      - /var/www/forjageek/static:/var/www/forjageek/static
      - /var/www/forjageek/media:/var/www/forjageek/media

    env_file:
      - .env

    command: >
      sh -c "python manage.py migrate &&
            python manage.py collectstatic --noinput &&
            gunicorn ForjaGeek.wsgi:application --bind 0.0.0.0:8000"

