# Generated by Django 6.1 on 2026-08-27 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_caracteristica', models.CharField(help_text='Ex: Escala, Grau/Grade, Pontos de Articulação, Altura (cm), Possui LED', max_length=100, unique=True)),
                ('tipo_dado', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('boolean', 'Sim/Não')], default='texto', max_length=20)),
            ],
            options={
                'verbose_name': 'Característica',
                'verbose_name_plural': 'Características',
                'ordering': ['nome_caracteristica'],
            },
        ),
        migrations.CreateModel(
            name='TipoColecionavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tipo', models.CharField(help_text='Ex: Action Figure, Model Kit, Funko Pop, Estátua', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de colecionável',
                'verbose_name_plural': 'Tipos de colecionáveis',
                'ordering': ['nome_tipo'],
            },
        ),
        migrations.CreateModel(
            name='ModeloColecionavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_personagem', models.CharField(max_length=255)),
                ('franquia', models.CharField(max_length=255)),
                ('fabricante', models.CharField(max_length=255)),
                ('codigo_barras_ean_jan', models.CharField(blank=True, help_text='Código EAN-13, JAN ou UPC impresso na caixa', max_length=13, null=True, unique=True)),
                ('codigo_fabricante_sku', models.CharField(blank=True, help_text='Código interno da marca (ex: BAN5061234, #42)', max_length=100, null=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='catalogo.tipocolecionavel')),
            ],
            options={
                'verbose_name': 'Modelo de colecionável',
                'verbose_name_plural': 'Catálogo de modelos',
                'ordering': ['franquia', 'nome_personagem'],
            },
        ),
        migrations.CreateModel(
            name='ModeloCaracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(help_text='Ex: 1/144, RG, 16, true, Polystone', max_length=255)),
                ('caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='catalogo.caracteristica')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_caracteristicas', to='catalogo.modelocolecionavel')),
            ],
            options={
                'verbose_name': 'Característica do modelo',
                'verbose_name_plural': 'Características dos modelos',
                'constraints': [models.UniqueConstraint(fields=('modelo', 'caracteristica'), name='uniq_modelo_caracteristica')],
            },
        ),
    ]
