# Generated by Django 6.1 on 2026-09-11 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristica',
            name='tipos',
            field=models.ManyToManyField(blank=True, related_name='caracteristicas', to='catalogo.tipocolecionavel'),
        ),
        migrations.AddField(
            model_name='modelocolecionavel',
            name='nome_modelo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='ImagemModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagem', models.URLField(max_length=500)),
                ('ordem_exibicao', models.IntegerField(default=0)),
                ('imagem_principal', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='catalogo.modelocolecionavel')),
            ],
            options={
                'ordering': ['ordem_exibicao', 'pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('imagem_principal', True)), fields=('modelo',), name='unica_principal_catalogo')],
            },
        ),
    ]
