# Generated by Django 6.1 on 2026-09-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_caracteristica_tipos_modelocolecionavel_nome_modelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristica',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='caracteristica',
            name='tipos',
            field=models.ManyToManyField(blank=True, db_table='tipos_caracteristicas', related_name='caracteristicas', to='catalogo.tipocolecionavel'),
        ),
        migrations.AlterField(
            model_name='imagemmodelo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='modelocaracteristica',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='modelocolecionavel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tipocolecionavel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='caracteristica',
            table='caracteristicas',
        ),
        migrations.AlterModelTable(
            name='imagemmodelo',
            table='imagens_modelos',
        ),
        migrations.AlterModelTable(
            name='modelocaracteristica',
            table='modelos_caracteristicas',
        ),
        migrations.AlterModelTable(
            name='modelocolecionavel',
            table='modelos_colecionaveis',
        ),
        migrations.AlterModelTable(
            name='tipocolecionavel',
            table='tipos_colecionaveis',
        ),
    ]
