# Generated by Django 5.2.17 on 2026-09-17 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0008_alter_colecionavelusuario_id_alter_diorama_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('colecionavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas', to='inventario.colecionavelusuario')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas_recebidas', to=settings.AUTH_USER_MODEL)),
                ('iniciado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas_iniciadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conversas',
                'ordering': ['-atualizada_em'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('enviada_em', models.DateTimeField(auto_now_add=True)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='core.conversa')),
            ],
            options={
                'db_table': 'mensagens',
                'ordering': ['enviada_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='conversa',
            constraint=models.UniqueConstraint(fields=('iniciado_por', 'destinatario', 'colecionavel'), name='uniq_conversa_anuncio'),
        ),
    ]
