# Generated by Django 6.1 on 2026-08-27 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransacaoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_item', models.DecimalField(decimal_places=2, max_digits=20)),
                ('taxa_plataforma', models.DecimalField(decimal_places=2, max_digits=20)),
                ('valor_liquido_vendedor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('whatsapp_comprador', models.CharField(help_text='Número de contato salvo no momento da compra', max_length=20)),
                ('whatsapp_vendedor', models.CharField(help_text='Número de contato do vendedor', max_length=20)),
                ('status_transacao', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('enviado', 'Enviado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('colecionavel_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='inventario.colecionavelusuario')),
            ],
            options={
                'verbose_name': 'Transação de venda',
                'verbose_name_plural': 'Transações de venda',
                'ordering': ['-criado_em'],
            },
        ),
    ]
