# Generated by Django 5.2.17 on 2026-09-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacaovenda',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transacaovenda',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transacaovenda',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='transacaovenda',
            table='transacoes_venda',
        ),
    ]
