# Generated by Django 5.2.17 on 2026-09-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0003_transacaovenda_stripe_checkout_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacaovenda',
            name='status_transacao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Pago'), ('concluida', 'Concluído'), ('cancelada', 'Cancelado')], default='pendente', max_length=50),
        ),
    ]
