# Generated by Django 5.2.17 on 2026-09-22 11:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0004_alter_transacaovenda_status_transacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoVenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField(help_text='Nota de 1 a 5 estrelas.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, max_length=700)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('avaliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_recebidas', to=settings.AUTH_USER_MODEL)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_feitas', to=settings.AUTH_USER_MODEL)),
                ('transacao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacao', to='transacoes.transacaovenda')),
            ],
            options={
                'verbose_name': 'Avaliação de venda',
                'verbose_name_plural': 'Avaliações de vendas',
                'db_table': 'avaliacoes_venda',
                'ordering': ['-criado_em'],
                'constraints': [models.CheckConstraint(condition=models.Q(('nota__gte', 1), ('nota__lte', 5)), name='avaliacao_venda_nota_entre_1_e_5')],
            },
        ),
    ]
