# Generated by Django 6.1 on 2026-09-17 12:04

import dioramas_novo.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0010_avaliacaoestante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DioramaPresetNovo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('descricao', models.CharField(max_length=300)),
                ('imagem_preview', models.ImageField(blank=True, upload_to='dioramas_novo/presets/')),
                ('prompt_base', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Preset de diorama (novo)',
                'verbose_name_plural': 'Presets de diorama (novo)',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DioramaGeradoNovo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('predefinido', 'Predefinido'), ('personalizado', 'Personalizado')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.ImageField(upload_to=dioramas_novo.models.caminho_diorama)),
                ('prompt_utilizado', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('colecionavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dioramas_gerados_novos', to='inventario.colecionavelusuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dioramas_gerados_novos', to=settings.AUTH_USER_MODEL)),
                ('preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dioramas', to='dioramas_novo.dioramapresetnovo')),
            ],
            options={
                'verbose_name': 'Diorama gerado (novo)',
                'verbose_name_plural': 'Dioramas gerados (novo)',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['usuario', '-data_criacao'], name='diorama_novo_usuario_idx')],
            },
        ),
    ]
